from . import Menu
from  . import Dastur_dars
from  . import Video
from . import frilans
from . import SMM
from . import fronted
from . import backend
from . import tgbot
from . import web
from . import mobil
from . import suniy
from . import oop
from . import c1